{{- if and .Values.enrollmentJwt.token (not .Values.enrollmentJwt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-router.fullname" . }}-jwt
type: Opaque
data:
  token: {{ required "You must set .Values.enrollmentJwt.token to the JWT from Ziti controller. ziti edge create edge-router <router-name>  --role-attributes \"public\" --tunneler-enabled --jwt-output-file /tmp/token.jwt" .Values.enrollmentJwt.token | b64enc }}
{{- end }}
